version: '3.5'

services:
  # Postgres - Prod
  postgres_prod:
    image: postgres:14.2-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Axoj2378"
      POSTGRES_DB: "prod_database"
    restart: unless-stopped
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - "./.env"

  # PostgreSQL - Dev
  postgres_dev:
    image: postgres:14.2-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Axoj2378"
      POSTGRES_DB: "dev_database"
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - "./.env"

  # Redis - Prod
  redis_prod:
    image: redis:latest
    container_name: redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - order_queue_prod:/root/redis
      - /usr/local/etc/redis-prod:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=fsdalgsd!@#lkjklj24398$
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  # Reids - Dev
  redis_dev:
    image: redis:latest
    container_name: redis-dev
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - order_queue_dev:/root/redis
      - /usr/local/etc/redis-dev:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=salkj22r3ls8!@
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  postgres_prod_data:
  postgres_dev_data:
  order_queue_prod:
  order_queue_dev: