version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis-${NAME}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - order_queue_${ENV}:/root/redis
      - /usr/local/etc/redis-${ENV}:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=16

volumes:
  order_queue_prod:
  order_queue_dev: